name: tester
on:
  push:
    branches: ['*']
  pull:
    branches: ['*']
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        images: mysql-latest
        port:
          3306:3306
        env:
          MYSQL_DATABASE: login-product
          MYSQL_PASSWORD: root
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Cai Node
        uses: actions/setup-node@v2
        with:
          node-version: '24'

      - name: Cai java
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cai dependency frontend
        run: |
          cd FloginFE_BE/frontend
          npm i

      - name: Frontend test
        run: |
          cd FloginFE_BE/frontend
          npm run test 
